version: "3.8"
services:
  back:
    environment:
      - NODE_ENV=development
    image: node:14.17.1-stretch
    working_dir: "/back"
    ports:
      ["8080:8080"]
    command:  sh -c "yarn install && yarn start-dev"
    volumes:
      - "./packages/back:/back"

  db:
    environment:
      - MONGO_USER=admin
      - MONGO_PASS=admin
    container_name: db
    image: mongo
    ports:
      ["27017:27017"]

  front:
    container_name: front
    stdin_open: true
    image: node:14.17.1-stretch
    working_dir: "/front"
    command: sh -c "yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - "./packages/front:/front"

volumes:
  back:
  front:

networks:
  default:
